baseURL = "https://brandonsnetwork.com/"
languageCode = "en-us"
title = "Brandon Lynch"
theme = "hugo-coder-nord"

[params]
	author = "Brandon Lynch"
	info = "Breaking into Cybersecurity"
	description = "Brandon Lynch's personal website"
	keywords = "brandon lynch,network,it,cybersecurity,infosec"
	colorScheme = "auto"

[[params.social]]
	name = "Github"
	icon = "fa fa-github fa-2x"
	weight = 1
	url = "https://github.com/brandonlynch2402"
	target = "_blank"
[[params.social]]
	name = "Twitter"
	icon = "fa fa-twitter fa-2x"
	weight = 3
	url = "https://twitter.com/thenetcode"
	target = "_blank"
[[params.social]]
	name = "LinkedIn"
	icon = "fa fa-linkedin fa-2x"
	weight = 3
	url = "https://www.linkedin.com/in/brandon-lynch-it"
	target = "_blank"

[[menu.main]]
	name = "About Me"
	weight = 1
	url = "about/"
[[menu.main]]
	name = "Blog"
	weight = 2
	url = "posts/"

[markup.goldmark.renderer]
unsafe = true
